ARM: dts: aspeed: mtmitchell: evt: fix missing i2c header
Add missing i2c header for compilation error below:
  FATAL ERROR: Unable to parse input tree

Signed-off-by: Thang Q. Nguyen <thang@os.amperecomputing.com>